USE SILVER;
GO

CREATE TABLE dbo.Member_Payment_Arrears (
    Mbr_Month_Key                  VARCHAR(30)   NULL,
    Membership_Id                  DECIMAL(9,0)  NOT NULL,
    Group_Id                       VARCHAR(20)   NULL,
    Cover                          VARCHAR(500)  NULL,
    Cover_Category                 VARCHAR(20)   NULL,
    Product_Code                   VARCHAR(15)   NULL,
    Date_Paid_To                   DATE          NULL,
    Join_Date                      DATETIME      NULL,
    Member_Arrears                 MONEY         NULL,
    Member_Advance                 MONEY         NULL,
    Member_Cont                    MONEY         NULL,
    Rundate                        DATE          NULL,
    Month_Year                     VARCHAR(9)    NULL,
    Member_Arrears_No_Other        MONEY         NULL,
    Member_Advance_No_Other        MONEY         NULL,
    Member_Arrears_Unearned        MONEY         NULL,
    Member_Arrears_Hosp            MONEY         NULL,
    Member_Advance_Hosp            MONEY         NULL,
    Member_Cont_Hosp               MONEY         NULL,
    Member_Arr_Unearned_Hosp       MONEY         NULL,
    Member_Arrears_Extras          MONEY         NULL,
    Member_Advance_Extras          MONEY         NULL,
    Member_Cont_Extras             MONEY         NULL,
    Member_Arr_Unearned_Extras     MONEY         NULL,
    Cover_State                    VARCHAR(3)    NULL,
    Branch_Group_Id                DECIMAL(9,0)  NULL,
    Branch_Description             VARCHAR(60)   NULL,
    Hosp_Product_Id                DECIMAL(9,0)  NULL,
    Extras_Product_Id              DECIMAL(9,0)  NULL,
    Ambuln_Product_Id              DECIMAL(9,0)  NULL,
    Cover_Type                     VARCHAR(1)    NULL,
    Billing_Freq                   VARCHAR(1)    NULL,
    Billing_Type                   VARCHAR(1)    NULL,
    Member_Advance_Days            INT           NULL,
    Advance_Days_Bracket           VARCHAR(12)   NULL,
    Member_Arrears_Days            INT           NULL,
    Arrears_Days_Bracket           VARCHAR(20)   NULL,
    Sales_Channel_Description      VARCHAR(60)   NULL,
    Billing_Freq_Description       VARCHAR(60)   NULL,
    Hear_About_Description         VARCHAR(60)   NULL,
    Promotion_Description          VARCHAR(60)   NULL,
    Agent_Description              VARCHAR(60)   NULL,
    Billing_Group_Description      VARCHAR(60)   NULL,
    Previous_Fund_Id               DECIMAL(9,0)  NULL,
    Previous_Fund_Description      VARCHAR(60)   NULL,
    Paying_Type                    VARCHAR(20)   NULL,
    Memship_Status                 VARCHAR(1)    NULL,
    Termination_Date               DATE          NULL,
    Entry_Termination_Date         DATE          NULL,
    No_Periods                     INT           NULL,
    Period_Description              VARCHAR(60)   NULL,
    TPT_Date                       DATE          NULL,
    Advance_Arrears_Flag           VARCHAR(7)    NULL,
    Arrears_Flag                   BIT           NULL,
    Mbr_Arrears_Key                VARCHAR(30)   NULL,
    Arrears_Month                  DATE          NULL,
    Termination_Month_Flag         VARCHAR(25)   NULL,
    Sixty_Days_Backdated           VARCHAR(20)   NULL,
    Payment_Change                 VARCHAR(25)   NULL,
    Count_Of_Dishonours            INT           NULL,
    Dishonour_Type                 VARCHAR(15)   NULL,
    Consec_Months                  INT           NULL
);
GO
