CREATE TABLE SILVER.dbo.Agent_Agreement_Renewal (
    [Agent ID]                                     DECIMAL(9,0)   NOT NULL,
    [group_type]                                    CHAR(1)        NULL,
    [Agency]                                        VARCHAR(60)    NULL,
    [Commencement Date]                             DATE           NULL,
    [Expiry Date]                                    DATE           NULL,
    [Discount Amount]                               DECIMAL(19,4)  NULL,
    [Agreement Status]                              VARCHAR(21)    NULL,
    [NPrint Flag]                                    VARCHAR(6)     NULL,
    [Agent Name]                                     VARCHAR(60)    NULL,
    [Termination Date]                              VARCHAR(20)    NULL,
    [create_operator]                               CHAR(16)       NULL,
    [Create Date]                                    DATE           NULL,
    [update_operator]                               CHAR(16)       NULL,
    [Update Date]                                    DATE           NULL,
    [Create Monthyear]                              VARCHAR(9)     NULL,
    [Member Agent Term Date]                        DATE           NULL,
    [Member Agent Commencement Date]                DATE           NULL,
    [membership_id]                                 DECIMAL(9,0)   NULL,
    [memship_status]                                CHAR(1)        NULL,
    [Current PTD]                                    DATE           NULL,
    [person_id]                                     DECIMAL(9,0)   NULL,
    [Ortto Key]                                      VARCHAR(19)    NULL,
    [Main Member Surname]                           VARCHAR(40)    NULL,
    [Form ID]                                        DECIMAL(9,0)   NULL,
    [create_datetime]                               DATETIME       NULL,
    [Has Form Generated Last 60 Days]               VARCHAR(3)     NULL,
    [LatestReceiptAmount]                           MONEY          NULL,
    [DiscountOnLatestReceipt]                       MONEY          NULL,
    [Discount%OnLatestReceipt]                      MONEY          NULL,
    [Product Description]                           NVARCHAR(MAX)  NULL,
    [Billing Frequency]                             VARCHAR(60)    NULL,
    [Group ID]                                       DECIMAL(9,0)   NULL,
    [Group Description]                             VARCHAR(60)    NULL,
    [Billing Group Commencement Date]               DATE           NULL,
    [membership_group_version]                      DECIMAL(9,0)   NULL,
    [Expired Agreement Active Member Agent Flag]    VARCHAR(4)     NULL,
    [Detrimental Comms Flag]                        VARCHAR(4)     NULL,
    [Member Added Within 60 Days]                   VARCHAR(4)     NULL
);
