CREATE TABLE SILVER.dbo.Dental_Financial_Detail (
    ACCTID              VARCHAR(45)     NULL,
    Create_Date         DATETIME2       NULL,
    Create_User         VARCHAR(8)      NULL,
    Post_Date           DATE            NULL,
    Period              INT             NULL,
    Journal_ID          DECIMAL(18,0)   NULL,
    Journal_Detail      VARCHAR(60)     NULL,
    Amount              DECIMAL(18,2)   NULL,
    Quantity            DECIMAL(18,0)   NULL,
    Journal_Ref         VARCHAR(60)     NULL,
    Fin_Year            INT             NULL,
    Fin_Period          INT             NULL,
    [Month]             TINYINT         NULL,
    Source              VARCHAR(10)     NULL,
    Budget_Version      VARCHAR(1)      NULL,
    Account_Display     VARCHAR(45)     NULL,
    Account_Name        VARCHAR(60)     NULL,
    Loc_Code            VARCHAR(15)     NULL,
    Branch              VARCHAR(60)     NULL,
    Account_Num         VARCHAR(15)     NULL
);
