-- NPS_Score validation query
-- Replicates the one active (non-commented-out) block in Qualtrics_NPS_Score.md:
-- CONCATENATE of all 6 surveys' BRONZE.qua tables, filtered to rows with a
-- non-blank "Member Number".
--
-- This is a validation query only, not a Stored Procedure -- for sharing with
-- a colleague to confirm the logic is correct before it gets wrapped into
-- usp_Load_NPS_Score.
--
-- Qlik's CONCATENATE aligns tables by column name (union of columns across
-- the 6 surveys, missing values filled with Null()) -- it does not require
-- the source tables to share identical columns or column counts. SQL's
-- UNION ALL instead requires every SELECT to return the same number of
-- columns in the same order, so each SELECT below explicitly lists every
-- column in the 55-column union across all 6 tables (verified against
-- INFORMATION_SCHEMA.COLUMNS and cross-checked against the 55-column result
-- from qualtrics_data_extract_fetch.ipynb's own pd.concat), with
-- NULL AS [ColumnName] for any column a given table does not have.

-- Qualtrics_CSAT
SELECT
    Survey_id,
    [Survey Name],
    ResponseId,
    StartDate,
    MonthYear,
    EndDate,
    Status,
    IPAddress,
    Duration,
    Recipient,
    Email,
    ExternalReference,
    LocationLatitude,
    LocationLongitude,
    [Customer Satisfaction Level],
    [Customer Satisfaction Score],
    [Customer Effort Level],
    [Customer Effort Score],
    [Net Promoter Level],
    [Net Promoter Score],
    [Resolved Today],
    [Fix Support],
    Feedback,
    [Comments for Marketing],
    Interaction,
    [Provider Group],
    [Provider/Program/Staff],
    Age,
    [Contact Reason],
    Product,
    Gender,
    [Member Number],
    [Member Type],
    Postcode,
    State,
    TenureMonths,
    Region,
    NULL AS [POC First Visit],
    NULL AS [POC How did you hear about],
    NULL AS [POC How did you hear about Other],
    NULL AS ProviderNo,
    NULL AS Agreement,
    NULL AS ClaimNo,
    NULL AS Operator,
    NULL AS Relationship,
    NULL AS [How did you hear],
    NULL AS [How did you hear Other],
    NULL AS [Likely to choose],
    NULL AS [Feedback Improvements],
    NULL AS PreviousFund,
    NULL AS Promotion,
    NULL AS [Achieve Goals],
    NULL AS [Effective Tools],
    NULL AS [How Quickly Contacted],
    NULL AS [Program Type]
FROM BRONZE.qua.Qualtrics_CSAT
WHERE LEN(LTRIM(RTRIM([Member Number]))) > 0

UNION ALL

-- Qualtrics_POC
SELECT
    Survey_id,
    [Survey Name],
    ResponseId,
    StartDate,
    MonthYear,
    EndDate,
    Status,
    IPAddress,
    Duration,
    Recipient,
    Email,
    ExternalReference,
    LocationLatitude,
    LocationLongitude,
    [Customer Satisfaction Level],
    [Customer Satisfaction Score],
    NULL AS [Customer Effort Level],
    NULL AS [Customer Effort Score],
    [Net Promoter Level],
    [Net Promoter Score],
    NULL AS [Resolved Today],
    NULL AS [Fix Support],
    Feedback,
    NULL AS [Comments for Marketing],
    Interaction,
    [Provider Group],
    [Provider/Program/Staff],
    Age,
    NULL AS [Contact Reason],
    Product,
    Gender,
    [Member Number],
    [Member Type],
    Postcode,
    State,
    TenureMonths,
    Region,
    [POC First Visit],
    [POC How did you hear about],
    [POC How did you hear about Other],
    ProviderNo,
    Agreement,
    ClaimNo,
    Operator,
    Relationship,
    NULL AS [How did you hear],
    NULL AS [How did you hear Other],
    NULL AS [Likely to choose],
    NULL AS [Feedback Improvements],
    NULL AS PreviousFund,
    NULL AS Promotion,
    NULL AS [Achieve Goals],
    NULL AS [Effective Tools],
    NULL AS [How Quickly Contacted],
    NULL AS [Program Type]
FROM BRONZE.qua.Qualtrics_POC
WHERE LEN(LTRIM(RTRIM([Member Number]))) > 0

UNION ALL

-- Qualtrics_HealthServices
SELECT
    Survey_id,
    [Survey Name],
    ResponseId,
    StartDate,
    MonthYear,
    EndDate,
    Status,
    IPAddress,
    Duration,
    Recipient,
    Email,
    ExternalReference,
    LocationLatitude,
    LocationLongitude,
    NULL AS [Customer Satisfaction Level],
    NULL AS [Customer Satisfaction Score],
    NULL AS [Customer Effort Level],
    NULL AS [Customer Effort Score],
    [Net Promoter Level],
    [Net Promoter Score],
    NULL AS [Resolved Today],
    NULL AS [Fix Support],
    Feedback,
    NULL AS [Comments for Marketing],
    Interaction,
    [Provider Group],
    [Provider/Program/Staff],
    Age,
    NULL AS [Contact Reason],
    Product,
    Gender,
    [Member Number],
    [Member Type],
    Postcode,
    State,
    TenureMonths,
    Region,
    NULL AS [POC First Visit],
    NULL AS [POC How did you hear about],
    NULL AS [POC How did you hear about Other],
    ProviderNo,
    NULL AS Agreement,
    NULL AS ClaimNo,
    NULL AS Operator,
    NULL AS Relationship,
    [How did you hear],
    [How did you hear Other],
    [Likely to choose],
    [Feedback Improvements],
    PreviousFund,
    Promotion,
    NULL AS [Achieve Goals],
    NULL AS [Effective Tools],
    NULL AS [How Quickly Contacted],
    NULL AS [Program Type]
FROM BRONZE.qua.Qualtrics_HealthServices
WHERE LEN(LTRIM(RTRIM([Member Number]))) > 0

UNION ALL

-- Qualtrics_MentalHealth
SELECT
    Survey_id,
    [Survey Name],
    ResponseId,
    StartDate,
    MonthYear,
    EndDate,
    Status,
    IPAddress,
    Duration,
    Recipient,
    Email,
    ExternalReference,
    LocationLatitude,
    LocationLongitude,
    [Customer Satisfaction Level],
    [Customer Satisfaction Score],
    NULL AS [Customer Effort Level],
    NULL AS [Customer Effort Score],
    [Net Promoter Level],
    [Net Promoter Score],
    NULL AS [Resolved Today],
    NULL AS [Fix Support],
    NULL AS Feedback,
    NULL AS [Comments for Marketing],
    Interaction,
    [Provider Group],
    [Provider/Program/Staff],
    Age,
    NULL AS [Contact Reason],
    Product,
    Gender,
    [Member Number],
    [Member Type],
    Postcode,
    State,
    TenureMonths,
    Region,
    NULL AS [POC First Visit],
    NULL AS [POC How did you hear about],
    NULL AS [POC How did you hear about Other],
    ProviderNo,
    NULL AS Agreement,
    NULL AS ClaimNo,
    NULL AS Operator,
    NULL AS Relationship,
    NULL AS [How did you hear],
    NULL AS [How did you hear Other],
    NULL AS [Likely to choose],
    [Feedback Improvements],
    PreviousFund,
    Promotion,
    [Achieve Goals],
    [Effective Tools],
    NULL AS [How Quickly Contacted],
    NULL AS [Program Type]
FROM BRONZE.qua.Qualtrics_MentalHealth
WHERE LEN(LTRIM(RTRIM([Member Number]))) > 0

UNION ALL

-- Qualtrics_Wellbeing
SELECT
    Survey_id,
    [Survey Name],
    ResponseId,
    StartDate,
    MonthYear,
    EndDate,
    Status,
    IPAddress,
    Duration,
    Recipient,
    Email,
    ExternalReference,
    LocationLatitude,
    LocationLongitude,
    [Customer Satisfaction Level],
    [Customer Satisfaction Score],
    NULL AS [Customer Effort Level],
    NULL AS [Customer Effort Score],
    [Net Promoter Level],
    [Net Promoter Score],
    NULL AS [Resolved Today],
    NULL AS [Fix Support],
    NULL AS Feedback,
    NULL AS [Comments for Marketing],
    Interaction,
    [Provider Group],
    [Provider/Program/Staff],
    Age,
    NULL AS [Contact Reason],
    Product,
    Gender,
    [Member Number],
    [Member Type],
    Postcode,
    State,
    TenureMonths,
    Region,
    NULL AS [POC First Visit],
    NULL AS [POC How did you hear about],
    NULL AS [POC How did you hear about Other],
    ProviderNo,
    NULL AS Agreement,
    NULL AS ClaimNo,
    NULL AS Operator,
    NULL AS Relationship,
    NULL AS [How did you hear],
    NULL AS [How did you hear Other],
    NULL AS [Likely to choose],
    [Feedback Improvements],
    PreviousFund,
    Promotion,
    [Achieve Goals],
    [Effective Tools],
    [How Quickly Contacted],
    NULL AS [Program Type]
FROM BRONZE.qua.Qualtrics_Wellbeing
WHERE LEN(LTRIM(RTRIM([Member Number]))) > 0

UNION ALL

-- Qualtrics_Wellbeing_V2
SELECT
    Survey_id,
    [Survey Name],
    ResponseId,
    StartDate,
    MonthYear,
    EndDate,
    Status,
    IPAddress,
    Duration,
    Recipient,
    Email,
    ExternalReference,
    LocationLatitude,
    LocationLongitude,
    [Customer Satisfaction Level],
    [Customer Satisfaction Score],
    NULL AS [Customer Effort Level],
    NULL AS [Customer Effort Score],
    [Net Promoter Level],
    [Net Promoter Score],
    NULL AS [Resolved Today],
    NULL AS [Fix Support],
    NULL AS Feedback,
    NULL AS [Comments for Marketing],
    Interaction,
    [Provider Group],
    [Provider/Program/Staff],
    Age,
    NULL AS [Contact Reason],
    Product,
    Gender,
    [Member Number],
    [Member Type],
    Postcode,
    State,
    TenureMonths,
    Region,
    NULL AS [POC First Visit],
    NULL AS [POC How did you hear about],
    NULL AS [POC How did you hear about Other],
    ProviderNo,
    NULL AS Agreement,
    NULL AS ClaimNo,
    NULL AS Operator,
    NULL AS Relationship,
    NULL AS [How did you hear],
    NULL AS [How did you hear Other],
    NULL AS [Likely to choose],
    [Feedback Improvements],
    PreviousFund,
    Promotion,
    NULL AS [Achieve Goals],
    NULL AS [Effective Tools],
    NULL AS [How Quickly Contacted],
    [Program Type]
FROM BRONZE.qua.Qualtrics_Wellbeing_V2
WHERE LEN(LTRIM(RTRIM([Member Number]))) > 0;
